import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import useAuth from "../../hooks/useAuth";
import { CheckIcon } from "@heroicons/react/outline";
import Table from "./Table";
import Loader from "./Loader";
import { loadCheckout } from "../../lib/stripe";
import Image from "next/image";

export default function Plans({ products }) {
  const { logout, user } = useAuth();
  const [selectedPlan, setSelectedPlan] = useState(products[2]);
  const [isBillingLoading, setBillingLoading] = useState(false);

  const subscribeToPlan = () => {
    if (!user) return;
    loadCheckout(selectedPlan?.prices[0].id);
    setBillingLoading(true);
  };

  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="  bg-black">
        <div className="w-[125px]">
          <Link href="/">
            <Image
              src="/netflixsocial.png"
              alt=""
              width={598}
              height={280}
              layout="responsive"
              className={`text-white cursor-pointer`}
            />
          </Link>
        </div>
        <button
          className="text-lg font-medium hover:underline"
          onClick={logout}
        >
          Sign Out
        </button>
      </header>

      <main className="pt-28 max-w-5xl mx-auto px-5 pb-12 transition-all md:px-10">
        <h1 className="mb-3 text-3xl font-medium">
          Choose the plan that&apos;s right for you
        </h1>
        <ul>
          <li className="flex items-center gap-x-2 text-lg">
            <CheckIcon className="h-7 w-7 text-[#E50914]" /> Watch all you want.
            Ad-free.
          </li>
          <li className="flex items-center gap-x-2 text-lg">
            <CheckIcon className="h-7 w-7 text-[#E50914]" /> Recommendations
            just for you.
          </li>
          <li className="flex items-center gap-x-2 text-lg">
            <CheckIcon className="h-7 w-7 text-[#E50914]" /> Change or cancel
            your plan anytime.
          </li>
        </ul>

        <div className="mt-4 flex flex-col space-y-4">
          <div className="flex w-full items-center self-end justify-center md:w-3/5">
            {products.map((product) => (
              <div
                key={product.id}
                className={`planBox ${
                  // selected plan has full opacity
                  selectedPlan?.id === product.id ? "opacity-100" : "opacity-60"
                }`}
                onClick={() => setSelectedPlan(product)}
              >
                {product.name}
              </div>
            ))}
          </div>
          <Table products={products} selectedPlan={selectedPlan} />

          <button
            disabled={!selectedPlan || isBillingLoading}
            className={`mx-auto w-11/12 rounded bg-[#E50914] py-4 text-xl shadow hover:bg-[#f6121d] md:w-[420px] ${
              isBillingLoading && "opacity-60"
            }`}
            onClick={subscribeToPlan}
          >
            {isBillingLoading ? (
              <Loader color="dark:fill-gray-300" />
            ) : (
              "Subscribe"
            )}
          </button>
        </div>
      </main>
    </div>
  );
}
