import React from "react";
import Head from "next/head";
import Sidebar from "../components/social/Sidebar";
import Feed from "../components/social/Feed";

export default function social() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />
        {/* Widgets */}
        {/* modal */}
      </main>
    </div>
  );
}
