import React from "react";
import Head from "next/head";
import Sidebar from "../components/social/Sidebar";
import Feed from "../components/social/Feed";
import { getProviders, getSession, useSession } from "next-auth/react";
import Login from "../components/social/Login";
import PostModal from "../components/social/PostModal";
import { useRecoilState } from "recoil";
import { modalState } from "../atoms/modalAtom";

export default function social({ providers }) {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);

  // if no session return the login componenet
  if (!session) return <Login providers={providers} />;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />

        {/* Widgets */}

        {isOpen && <PostModal />}
      </main>
    </div>
  );
}

// api requests are rendered server side
export async function getServerSideProps(context) {
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      providers,
      session,
    },
  };
}
